### ISSUE TITLE
Missing Retrigger output on the Network module.

### ISSUE THREAD

**Issue by aastle** [JustMog/Mog-VCV#3]
As the title suggests, I'm not finding a re-trigger output on the Network module when added to a patch.  I am comparing the actual module layout to the screen capture of the module in the Readme file.  The re-trigger output in the screen capture is in the lower right of the module.

![Network_Screen_Capture](https://user-images.githubusercontent.com/2071081/74241113-5bb51700-4ca9-11ea-89be-89ee2102b8d4.PNG)

**Comment by JustMog** [comment]
Hi, this is because the github master branch (& associated readme) is slightly ahead of the version available in vcv library currently. Expect to see the retrig feature added in the next update.
My bad, apologies for the confusion.
